version: '3.5'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app-network

  pgsql:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currencyExchangedb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - "db-data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - pgsql

networks:
  app-network:
    driver: bridge
volumes:
  db-data: